apiVersion: apps/v1
kind: Deployment
metadata:
  name: stapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stapp
  template:
    metadata:
      labels:
        app: stapp
    spec:
      containers:
        - name: stapp-container
          image: kruthim/stapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
