apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
    - port: ${APP_PORT} # Service port inside cluster (example: 8100)
      targetPort: ${APP_PORT} # Container port (same)
      nodePort: ${NODE_PORT} # Port accessible from host/Postman (example: 30081)
