apiVersion: v1
kind: Service
metadata:
  name: stapp-service
spec:
  type: NodePort
  selector:
    app: stapp
  ports:
    - port: 8100        # Service port inside the cluster
      targetPort: 8100  # Container port
      nodePort: 30082   # Port accessible on host/Postman
